services:
  app:
    build: ./app
    container_name: web-app  
    hostname: web-app
    volumes: ['./app/src:/appcode']
    ports:
      - 8501:8501
    networks:
      - app-network

  api:
    build: ./api
    container_name: web-api
    hostname: web-api
    volumes: ['./api:/apicode']
    ports:
      - 4000:4000
    networks:
      - app-network
    

  db:
    env_file:
      - ./api/.env
    image: mysql:9
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=project_susy_baka
    hostname: db
    volumes:
      - ./database-files:/docker-entrypoint-initdb.d/:ro
    ports:
      - 3200:3306
    networks:
      - app-network



networks:
  app-network:
    driver: bridge